name 'bacchus-web'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bacchus-web'
long_description 'Installs/Configures bacchus-web'
version '0.1.0'
